[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'w0ng/vim-hybrid'# {{{
hook_add = """
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme hybrid
"""# }}}
[[plugins]]
repo = 'osyo-manga/vim-precious'# {{{
dapends = ['context_filetype.vim']
if = 'g:light'
on_ft = ['toml']
hook_add = '''
let g:precious_enable_switch_CursorMoved = {
  \  "*" : 0,
  \  "toml" : 1,
  \}
'''# }}}
[[plugins]]
repo = 'Shougo/context_filetype.vim'# {{{
if = 'g:light'
on_ft = ['toml']# }}}
[[plugins]]
repo = 'cespare/vim-toml'# {{{
on_ft = 'toml'# }}}
[[plugins]]
repo = 'itchyny/vim-parenmatch'
[[plugins]]
repo = 'itchyny/vim-cursorword'
[[plugins]]
repo = 'tyru/caw.vim'# {{{
hook_add = '''
  nmap <C-I> <Plug>(caw:hatpos:toggle)
  vmap <C-I> <Plug>(caw:hatpos:toggle)
'''# }}}
[[plugins]]
repo = 'Shougo/unite.vim'# {{{
hook_add = '''
  let g:unite_enable_start_insert = 1

  augroup MyAutoCmd
    autocmd Filetype unite imap <buffer><silent> <ESC> <ESC>q
    autocmd Filetype unite imap <buffer><silent> <C-J> <C-N>
    autocmd Filetype unite imap <buffer><silent> <C-K> <C-P>
  augroup END

  nnoremap <silent> <Leader>b :Unite buffer<CR>
  nnoremap <silent> <Leader>a :Unite outline<CR>

  " Unite-grep {{{
  let g:unite_enable_ignore_case = 1
  let g:unite_enable_smart_case = 1

  nnoremap <silent> ,g  :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
  nnoremap <silent> ,cg :<C-u>Unite grep:. -buffer-name=search-buffer<CR><C-R><C-W>
  nnoremap <silent> ,r  :<C-u>UniteResume search-buffer<CR>

  " use ripgrep
  if executable('rg')
    let g:unite_source_grep_command = 'rg'
    let g:unite_source_grep_default_opts = '--vimgrep'
    let g:unite_source_grep_recursive_opt = ''
  endif
  
  " }}}
'''# }}}
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'scrooloose/nerdtree'# {{{
depends = ['vimproc.vim']
hook_add = '''
  nnoremap <silent> <Leader>s :NERDTree<CR>
  augroup MyAutoCmd
    au FileType nerdtree nmap <buffer> za o
    au FileType nerdtree nnoremap <buffer><silent> <Leader>s :q<CR>
  augroup END
'''# }}}
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'# {{{
depends = ['nerdtree']# }}}
[[plugins]]
repo = 'Shougo/vimshell.vim'# {{{
depends = ['vimproc.vim']
hook_add = '''
  nnoremap <silent> <Leader>h :VimShell<CR>
'''# }}}
[[plugins]]
repo = 'Shougo/neosnippet.vim'# {{{
depends = ['neosnippet-snippets']
hook_add = '''
  let g:neosnippet#snippets_directory = ['~/vimfiles/snippets/', '~/lib-cpp/']

  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_or_target)
'''# }}}
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'Shougo/neocomplete.vim'# {{{
hook_add = '''
  " setup {{{
  let g:acp_enableAtStartup = 0
  " Use neocomplete.
  let g:neocomplete#enable_at_startup = 1
  " Use smartcase.
  let g:neocomplete#enable_smart_case = 1

  " Define dictionary.
  let g:neocomplete#sources#dictionary#dictionaries = {
      \ 'default' : '',
      \ 'vimshell' : $HOME.'/.vimshell_hist',
      \ 'scheme' : $HOME.'/.gosh_completions'
      \ }

  " Define keyword.
  if !exists('g:neocomplete#keyword_patterns')
      let g:neocomplete#keyword_patterns = {}
  endif
  let g:neocomplete#keyword_patterns['default'] = '\h\w*'

  " Plugin key-mappings.
  inoremap <expr><C-g>     neocomplete#undo_completion()
  inoremap <expr><C-l>     neocomplete#complete_common_string()

  " Recommended key-mappings.
  " <CR>: close popup and save indent.
  inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
  function! s:my_cr_function()
    return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
    " For no inserting <CR> key.
    "return pumvisible() ? "\<C-y>" : "\<CR>"
  endfunction
  " <TAB>: completion.
  inoremap <silent><expr> <TAB>
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ neocomplete#start_manual_complete()
  function! s:check_back_space() abort "{{{
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~ '\s'
  endfunction"}}}
  " <C-h>, <BS>: close popup and delete backword char.
  inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
  inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
  " Close popup by <Space>.
  "inoremap <expr><Space> pumvisible() ? "\<C-y>" : "\<Space>"

  " AutoComplPop like behavior.
  "let g:neocomplete#enable_auto_select = 1

  " Shell like behavior (not recommended.)
  "set completeopt+=longest
  "let g:neocomplete#enable_auto_select = 1
  "let g:neocomplete#disable_auto_complete = 1
  "inoremap <expr><TAB>  pumvisible() ? "\<Down>" :
  " \ neocomplete#start_manual_complete()

  " Enable omni completion.
  autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
  autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
  autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
  autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
  autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

  " Enable heavy omni completion.
  if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
  endif
  if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
  endif
  "let g:neocomplete#sources#omni#input_patterns.php =
  "\ '[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
  "let g:neocomplete#sources#omni#input_patterns.c =
  "\ '[^.[:digit:] *\t]\%(\.\|->\)\%(\h\w*\)\?'
  "let g:neocomplete#sources#omni#input_patterns.cpp =
  "\ '[^.[:digit:] *\t]\%(\.\|->\)\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'

  " For perlomni.vim setting.
  " https://github.com/c9s/perlomni.vim
  let g:neocomplete#sources#omni#input_patterns.perl =
  \ '[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'

  " For smart TAB completion.
  "inoremap <expr><TAB>  pumvisible() ? "\<C-n>" :
  "        \ <SID>check_back_space() ? "\<TAB>" :
  "        \ neocomplete#start_manual_complete()
  "  function! s:check_back_space() "{{{
  "    let col = col('.') - 1
  "    return !col || getline('.')[col - 1]  =~ '\s'
  "  endfunction"}}}

  "  --- }}}

  " cpp {{{
  if !exists('g:neocomplete#force_omni_input_patterns')
      let g:neocomplete#force_omni_input_patterns = {}
  endif
  " let g:neocomplete#force_omni_input_patterns.cpp =
          " \ '[^.[:digit:] *\t]\%(\.\|->\)\w*\|\h\w*::\w*'
  " }}}

  " js {{{
  autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
  " }}}

'''# }}}
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_setConceal = 0
'''
# c++ {{{
[[plugins]]
repo = 'Mizuchi/STL-Syntax'# {{{
on_ft = 'cpp'# }}}
[[plugins]]
repo = 'Shougo/unite-outline'
[[plugins]]
repo = 'w0rp/ale'# {{{
if = 'has("job") && has("channel") && has("timers")'
on_ft = ['cpp', 'javascript']
# 参考 :
# https://rcmdnk.com/blog/2017/09/25/computer-vim/
# https://qiita.com/lighttiger2505/items/e0ada17634516c081ee7#ale
hook_add = '''
  " エラー行に表示するマーク
  if has('unix') && !has('gui_running')
    let g:ale_sign_error = '>>'
    let g:ale_sign_warning = '⚠'
  endif

  let g:ale_list_window_size = 1

  " エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  " エラー表示の列を常時表示
  let g:ale_sign_column_always = 1

  let g:ale_lint_on_enter = 1
  let g:ale_lint_on_save = 1
  " let g:ale_lint_on_text_changed = 'never'
  let g:ale_lint_on_insert_leave = 1

  let g:ale_set_loclist = 1
  let g:ale_set_quickfix = 0
  let g:ale_open_list = 0
  let g:ale_keep_list_window_open = 0

  let g:ale_linters = {
    \  'cpp': ['gcc'],
    \  'javascript': ['eslint'],
    \}

  let g:ale_javascript_prettier_use_local_config = 1

  let g:ale_fixers = {
  \   'javascript': [
  \       'prettier-eslint',
  \   ],
  \   'cpp': [
  \       'clang-format',
  \   ]
  \}

  let g:ale_javascript_prettier_use_local_config = 1

  nmap <silent> <Leader>p <Plug>(ale_previous_wrap)
  nmap <silent> <Leader>n <Plug>(ale_next_wrap)
  nnoremap <F8> :ALEFix<CR>

  function! s:ale_list()
    let g:ale_open_list = 1
    call ale#Queue(0, 'lint_file')
  endfunction
  command! ALEList call s:ale_list()
  nnoremap <Leader>m :ALEList<CR>
  autocmd MyAutoCmd FileType qf nnoremap <silent> <buffer> q :let g:ale_open_list = 0<CR>:bd<CR>
  autocmd MyAutoCmd FileType help,qf,man,ref let b:ale_enabled = 0
'''

hook_source = '''
  call ale#Set('cpp_gcc_options', '-std=c++14 -Wall -Wextra -DDEBUG -DDEBUG_OUT=cout')
'''# }}}
# }}}
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'# {{{
# 参考 :
# https://qiita.com/ahiruman5/items/4f3c845500c172a02935
hook_add = '''
  let g:ctrlp_match_window = 'bottom,order:ttb,min:1,max:20,results:50'
  let g:ctrlp_show_hidden = 1
  " ファイルのみ
  let g:ctrlp_types = ['fil']
  " カレントディレクトリから探す
  let g:ctrlp_working_path_mode = 'w'
  let g:ctrlp_lazy_update = 200
  let g:ctrlp_custom_ignore = {
    \ 'dir':  '\v([\/]\.(git|hg|svn)$|node_modules)',
    \ 'file': '\v\.(exe|so|dll|o)$',
    \ 'link': '',
    \ }
  " C-Rでキャッシュ削除
  let g:ctrlp_prompt_mappings = { 'PrtClearCache()': ['<C-R>'] }
  if executable('ag')
    " CtrlPのキャッシュを使わない
    let g:ctrlp_use_caching=0
    let g:ctrlp_user_command='ag %s -i --hidden -g ""'
  endif
'''#}}}
[[plugins]]
repo = 'thinca/vim-quickrun'# {{{
hook_add = '''
let g:quickrun_config = get(g:, 'quickrun_config', {})
let g:quickrun_config._ = {
  \ 'outputter' : 'quickfix',
  \ 'runner' : 'job'
  \ }

  let g:quickrun_config.cpp = {
  \ 'command' : 'g++',
  \ 'cmdopt' : '-DDEBUG -DDEBUG_OUT=cout -w -std=c++14',
  \ }

  " TODO : use this
  let g:quickrun_config['cpp/no-debbug'] = {
  \ 'command' : 'g++',
  \ 'cmdopt' : '-w -std=c++14',
  \ }
'''# }}}
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
[[plugins]]
repo = 'majutsushi/tagbar'# {{{
hook_add = '''
  let g:tagbar_width = 30
  let g:tagbar_autoshowtag = 1
'''# }}}
[[plugins]]
repo = 'elzr/vim-json'# {{{
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''# }}}
[[plugins]]
repo = 'ap/vim-buftabline'# {{{
hook_add = '''
  let g:buftabline_show = 1
  let g:buftabline_indicators = 1
'''# }}}
[[plugins]]
repo = 'rhysd/wandbox-vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'# {{{
build = 'make'# }}}
[[plugins]]
repo = 'pangloss/vim-javascript'# {{{
on_ft = ['javascript']# }}}
[[plugins]]
repo = 'digitaltoad/vim-pug'# {{{
on_ft = ['pug', 'jade']# }}}
[[plugins]]
repo = 'heavenshell/vim-jsdoc'# {{{
hook_add = '''
  let g:jsdoc_enable_es6 = 1
  au FileType javascript nnoremap <buffer> <Leader>d :JsDoc
'''# }}}
[[plugins]]
repo = 'ternjs/tern_for_vim'# {{{
build = 'npm install'
on_ft = ['javascript']
hook_add = '''
  au FileType javascript nnoremap <buffer><silent> <Leader>g :TernDef<CR>
'''# }}}

