[[plugins]]
repo = 'Shougo/dein.vim'

# hybrid {{{
[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = """
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme hybrid
"""
# }}}

# toml syntax{{{
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
# }}}

# parentmatch{{{
[[plugins]]
repo = 'itchyny/vim-parenmatch'
# }}}

# cursorword{{{
[[plugins]]
repo = 'itchyny/vim-cursorword'
# }}}

# comment out{{{
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  nmap <C-I> <Plug>(caw:hatpos:toggle)
  vmap <C-I> <Plug>(caw:hatpos:toggle)
'''
# }}}

# unite{{{
[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
  nnoremap <silent> <SPACE>b :Unite buffer<CR>
'''
# }}}

# gitgutter{{{
[[plugins]]
repo = 'airblade/vim-gitgutter'
# }}}

# NERDTree{{{
[[plugins]]
repo = 'scrooloose/nerdtree'
depends = ['vimproc.vim']
hook_add = '''
  nnoremap <silent> <SPACE>n :NERDTree<CR>
  augroup MyAutoCmd
    au FileType nerdtree nmap <buffer> za o
    au FileType nerdtree nnoremap <buffer><silent> <SPACE>n :q<CR>
  augroup END
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['nerdtree']
# }}}

# vimshell{{{
[[plugins]]
repo = 'Shougo/vimshell.vim'
depends = ['vimproc.vim']
hook_add = '''
  nnoremap <silent> <SPACE>sh :VimShell<CR>
'''
# }}}

# neosnippet{{{
[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
hook_add = '''
  let g:neosnippet#snippets_directory='~/vimfiles/snippets/'

  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_or_target)
'''
# }}}

# neosnippet-snippets{{{
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
# }}}

# neocomplete {{{
[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = '''
  " setup {{{
  let g:acp_enableAtStartup = 0
  " Use neocomplete.
  let g:neocomplete#enable_at_startup = 1
  " Use smartcase.
  let g:neocomplete#enable_smart_case = 1

  " Define dictionary.
  let g:neocomplete#sources#dictionary#dictionaries = {
      \ 'default' : '',
      \ 'vimshell' : $HOME.'/.vimshell_hist',
      \ 'scheme' : $HOME.'/.gosh_completions'
      \ }

  " Define keyword.
  if !exists('g:neocomplete#keyword_patterns')
      let g:neocomplete#keyword_patterns = {}
  endif
  let g:neocomplete#keyword_patterns['default'] = '\h\w*'

  " Plugin key-mappings.
  inoremap <expr><C-g>     neocomplete#undo_completion()
  inoremap <expr><C-l>     neocomplete#complete_common_string()

  " Recommended key-mappings.
  " <CR>: close popup and save indent.
  inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
  function! s:my_cr_function()
    return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
    " For no inserting <CR> key.
    "return pumvisible() ? "\<C-y>" : "\<CR>"
  endfunction
  " <TAB>: completion.
  inoremap <silent><expr> <TAB>
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ neocomplete#start_manual_complete()
  function! s:check_back_space() abort "{{{
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~ '\s'
  endfunction"}}}
  " <C-h>, <BS>: close popup and delete backword char.
  inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
  inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
  " Close popup by <Space>.
  "inoremap <expr><Space> pumvisible() ? "\<C-y>" : "\<Space>"

  " AutoComplPop like behavior.
  "let g:neocomplete#enable_auto_select = 1

  " Shell like behavior (not recommended.)
  "set completeopt+=longest
  "let g:neocomplete#enable_auto_select = 1
  "let g:neocomplete#disable_auto_complete = 1
  "inoremap <expr><TAB>  pumvisible() ? "\<Down>" :
  " \ neocomplete#start_manual_complete()

  " Enable omni completion.
  autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
  autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
  autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
  autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
  autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

  " Enable heavy omni completion.
  if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
  endif
  if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
  endif
  "let g:neocomplete#sources#omni#input_patterns.php =
  "\ '[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
  "let g:neocomplete#sources#omni#input_patterns.c =
  "\ '[^.[:digit:] *\t]\%(\.\|->\)\%(\h\w*\)\?'
  "let g:neocomplete#sources#omni#input_patterns.cpp =
  "\ '[^.[:digit:] *\t]\%(\.\|->\)\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'

  " For perlomni.vim setting.
  " https://github.com/c9s/perlomni.vim
  let g:neocomplete#sources#omni#input_patterns.perl =
  \ '[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'

  " For smart TAB completion.
  "inoremap <expr><TAB>  pumvisible() ? "\<C-n>" :
  "        \ <SID>check_back_space() ? "\<TAB>" :
  "        \ neocomplete#start_manual_complete()
  "  function! s:check_back_space() "{{{
  "    let col = col('.') - 1
  "    return !col || getline('.')[col - 1]  =~ '\s'
  "  endfunction"}}}

  "  --- }}}

  " cpp {{{
  if !exists('g:neocomplete#force_omni_input_patterns')
      let g:neocomplete#force_omni_input_patterns = {}
  endif
  let g:neocomplete#force_omni_input_patterns.cpp =
          \ '[^.[:digit:] *\t]\%(\.\|->\)\w*\|\h\w*::\w*'
  " }}}
'''
# }}}

# indent visualization {{{
[[plugins]]
repo = 'Yggdroot/indentLine'
# }}}

# c++ {{{
[[plugins]]
repo = 'Mizuchi/STL-Syntax'
on_ft = 'cpp'

# Snowdrop {{{
[[plugins]]
repo = 'osyo-manga/vim-snowdrop'
depends = ['vimproc.vim']
hook_add = '''
  if has("unix")
    let g:snowdrop#libclang_directory="/usr/lib/clang+llvm-3.4.2/lib"
  endif
  let g:snowdrop#command_options = {
    \"cpp" : "-std=c++14",
    \}

  " Enable code completion in neocomplete.vim.
  let g:neocomplete#sources#snowdrop#enable = 1

  " Not skip
  let g:neocomplete#skip_auto_completion_time = ""

  augroup MyAutoCmd
    autocmd FileType cpp setlocal balloonexpr=snowdrop#ballonexpr_typeof()
    autocmd FileType cpp setlocal ballooneval
  augroup END

  " 編集中にGotoDefinitionすると必ずエラーになるので
  let g:snowdrop#goto_definition_open_cmd = "silent! edit"

  " コマンドが登録されない謎バグ
  " issue出したほうがいいかね
  augroup MyAutoCmd
    autocmd FileType cpp call snowdrop#ftplugin#command("cpp")
    autocmd FileType cpp nnoremap <buffer><silent> <SPACE>i :SnowdropEchoTypeof<CR>
    autocmd FileType cpp nnoremap <buffer><silent> <SPACE>r :SnowdropEchoResultTypeof<CR>
    autocmd FileType cpp nnoremap <buffer><silent> <SPACE>g :SnowdropGotoDefinition<CR>
  augroup END
'''
# }}}

[[plugins]]
repo = 'Shougo/unite-outline'

# ALE {{{
[[plugins]]
repo = 'w0rp/ale'
if = 'has("job") && has("channel") && has("timers")'
on_ft = 'cpp'
# 参考 :
# https://rcmdnk.com/blog/2017/09/25/computer-vim/
# https://qiita.com/lighttiger2505/items/e0ada17634516c081ee7#ale
hook_add = '''
  " エラー行に表示するマーク
  let g:ale_sign_error = '>'
  let g:ale_sign_warning = '⚠'

  let g:ale_list_window_size = 1

  " エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  " エラー表示の列を常時表示
  let g:ale_sign_column_always = 1

  let g:ale_lint_on_enter = 1
  let g:ale_lint_on_save = 1
  " let g:ale_lint_on_text_changed = 'never'
  let g:ale_lint_on_insert_leave = 1

  let g:ale_set_loclist = 1
  let g:ale_set_quickfix = 0
  let g:ale_open_list = 0
  let g:ale_keep_list_window_open = 0

  let g:ale_linters = {
    \  'cpp': ['gcc'],
    \}

  nmap <silent> <C-K><C-P> <Plug>(ale_previous_wrap)
  nmap <silent> <C-K><C-N> <Plug>(ale_next_wrap)

  function! s:ale_list()
    let g:ale_open_list = 1
    call ale#Queue(0, 'lint_file')
  endfunction
  command! ALEList call s:ale_list()
  nnoremap <SPACE>m :ALEList<CR>
  autocmd MyAutoCmd FileType qf nnoremap <silent> <buffer> q :let g:ale_open_list = 0<CR>:q!<CR>
  autocmd MyAutoCmd FileType help,qf,man,ref let b:ale_enabled = 0
'''
# }}}

# }}}

# vim-airline {{{
[[plugins]]
repo = 'vim-airline/vim-airline'
if = 'g:light'
# 参考 :
# https://qiita.com/lighttiger2505/items/e0ada17634516c081ee7#vim-airline
hook_add = '''
  " モードの表示名を定義
  let g:airline_mode_map = {
    \ '__' : '-',
    \ 'n'  : 'N',
    \ 'i'  : 'I',
    \ 'R'  : 'R',
    \ 'c'  : 'C',
    \ 'v'  : 'V',
    \ 'V'  : 'V',
    \ ''  : 'V',
    \ 's'  : 'S',
    \ 'S'  : 'S',
    \ ''  : 'S',
    \ }

  let g:airline_powerline_fonts = 1
  let g:airline_theme = 'bubblegum'
  let g:airline#extensions#tabline#enabled = 1
  let g:ale_list_window_size = 4

  " gitのHEADから変更した行の+-を非表示(vim-gitgutterの拡張)
  let g:airline#extensions#hunks#enabled = 0

  " Lintツールによるエラー、警告を表示(ALEの拡張)
  let g:airline#extensions#ale#enabled = 1
  let g:airline#extensions#ale#error_symbol = 'E:'
  let g:airline#extensions#ale#warning_symbol = 'W:'
'''

hook_source = '''
  " let g:airline_section_z = airline#section#create(['windowswap', '%3p%% ', 'linenr', ':%3v'])
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
if = 'g:light'

# }}}

# CtrlP {{{
# 参考 :
# https://qiita.com/ahiruman5/items/4f3c845500c172a02935
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
  let g:ctrlp_match_window = 'bottom,order:ttb,min:1,max:20,results:50'
  let g:ctrlp_show_hidden = 1
  " ファイルのみ
  let g:ctrlp_types = ['fil']
  " カレントディレクトリから探す
  let g:ctrlp_working_path_mode = 'w'
  let g:ctrlp_lazy_update = 200
  let g:ctrlp_custom_ignore = {
    \ 'dir':  '\v[\/]\.(git|hg|svn)$',
    \ 'file': '\v\.(exe|so|dll|o)$',
    \ 'link': '',
    \ }
  " C-Rでキャッシュ削除
  let g:ctrlp_prompt_mappings = { 'PrtClearCache()': ['<C-R>'] }
  if executable('ag')
    " CtrlPのキャッシュを使わない
    let g:ctrlp_use_caching=0
    let g:ctrlp_user_command='ag %s -i --hidden -g ""'
  endif
'''

# }}}

# vim-quickrun {{{
[[plugins]]
repo = 'thinca/vim-quickrun'
# }}}

# japanese {{{
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
# }}}

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
hook_add = '''
  let g:gen_tags#gtags_auto_gen = 1
'''

[[plugins]]
repo = 'rhysd/wandbox-vim'
depends = ['vim-quickrun']

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug', 'jade', 'vue']

